add the session token into the header after the sign
EMCECS/ecs-object-client-java pull request #48
Opened 2021-04-28 07:42 UTC by shy950521

2021-04-28 22:03 UTC, twincitiesguy requested changes
I don't see any v4 signer in the target branch - maybe this is targeting the wrong branch for v4 auth - but you will also need to add the logic to the v4 signer

2021-04-29 10:32 UTC, shy950521 commented on src/main/java/com/emc/object/s3/S3SignerV2.java
> +        if (s3Config.getSessionToken() != null) {
As I mentioned in the email, boto3 added token into params['SecurityToken'] in V2 signing, not sure whether the header works here. Still working on deploying the testbed, I will update it when I finished the test.

2021-04-29 10:33 UTC, shy950521 commented
> I don't see any v4 signer in the target branch - maybe this is targeting the wrong branch for v4 auth - but you will also need to add the logic to the v4 signer

the PR shared the same target branch of the V4 PR, I will update the V4 part when the v4 PR is merged

2021-04-30 10:04 UTC, shy950521 commented on src/main/java/com/emc/object/s3/S3SignerV2.java
> +        if (s3Config.getSessionToken() != null) {
moved to the headers.

2021-07-29 14:13 UTC, twincitiesguy commented
what's the status of this draft?  has this already been merged by other PRs?

2023-12-04 07:49 UTC, closed without merging